version: 2.1
workflows:
  main:
    jobs:
      - release:
          context: falco
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
